version: "3"

tasks:
  aws-creds:
    cmds:
      - echo "Task - testing provider"
      - go clean -modcache
      - go test ./test/provider_test.go -v
  debug:
    cmds:
      - echo "Task - testing provider with visible browser and added logging"
      - go clean -modcache
      - go test ./test/provider_test.go -v -rod="show,slow=1s,trace"
  cli:
    cmds:
      - echo "Task - running interactive CLI"
      - go clean -testcache
      - go run ./scripts/cli.go  -v 
  cli-debug:
    cmds:
      - echo "Task - running interactive CLI"
      - go clean -testcache
      - go run ./scripts/cli.go -v -rod="show,slow=1s,trace"
  test-all:
    cmds:
      - echo "Task - testing all methods"
      - go clean -modcache
      - cd /test
      - go test -v
  test-gh-secret:
    cmds:
      - echo "***Testing GitHub API***"
      - go clean -modcache
      # SECRET_NAME SECRET_VAL
      - go test ./test/github_test.go -v -owner josephedward -repo gosandbox {{.CLI_ARGS}}
      