version: "3"

tasks:
  devtools:
    cmds:
      - echo "***Starting Devtools Session***"
      - go clean -modcache
      - $("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --remote-debugging-port=9222)
  auth:
    cmds:
      - echo "***Authenticating with ACloudGuru***"
      - go run ./test/authenticate.go  -v -rod="show,trace" {{.CLI_ARGS}}
  main:
    cmds:
      - echo "***Running CLI***"
      - go clean -testcache
      - go run ./main.go  
  debug-cli:
    cmds:
      - echo "***Running CLI***"
      - go clean -testcache
      - go run ./main.go -v -rod="show,trace"
  provider:
    cmds:
      - echo "***Testing Provider***"
      - go clean -modcache
      - go test ./test/provider_test.go -v -rod="show,trace"
  set-github:
    cmds:
      - echo "***Pushing Secrets to GitHub Repo***"
      - go clean -modcache
      - go test ./test/github_test.go -v -owner josephedward -repo gosandbox {{.CLI_ARGS}}
  db:
    cmds: 
      - echo "***Creating Database***"
      - go clean -modcache
      - go test ./test/db_test.go -v -rod="show,trace"
  test:
    cmds:
      - echo "***Running All Tests***"
      - go clean -modcache
      - cd /test
      - go test -v

  # manager:
  #   cmds: 
  #     - echo "***Connecting to Rod Container using launcher.Manager***"
  #     - go clean -modcache
  #     - docker run -p 7317:7317 ghcr.io/go-rod/rod
  #     # - go run ./manager.go 
  # remote:
  #   cmds: 
  #     - echo "***Connecting to Rod Container using launcher.Manager***"
  #     - go clean -modcache
  #     - go run ./remote.go -v -rod="show,trace"