version: "3"

tasks:
  cli:
    cmds:
      - echo "***Running CLI***"
      - go clean -testcache
      - go run ./main.go -v 
  cli-vis:
    cmds:
      - echo "***Running CLI***"
      - go clean -testcache
      - go run ./main.go -v -rod="show,trace"
  provider:
    cmds:
      - echo "***Testing Provider***"
      - go clean -modcache
      - go test ./test/provider_test.go -v -rod="show,trace"
  set-github:
    cmds:
      - echo "***Pushing Secrets to GitHub Repo***"
      - go clean -modcache
      - go test ./test/github_test.go -v -owner josephedward -repo gosandbox {{.CLI_ARGS}}
  db:
    cmds: 
      - echo "***Creating Database***"
      - go clean -modcache
      - go test ./test/db_test.go -v -rod="show,trace"
  test:
    cmds:
      - echo "***Running All Tests***"
      - go clean -modcache
      - cd /test
      - go test -v
