name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: josephedward
          password: ${{ secrets.GOSANDBOX }}
          registry: ghcr.io
          repository: josephedward/gosandbox/alpha-v1
          tag_with_sha: true